/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUserManagementRouteImport } from './routes/_authenticated/user-management'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedParticipantsRouteImport } from './routes/_authenticated/participants'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedInstructionsRouteImport } from './routes/_authenticated/instructions'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedBrainRouteImport } from './routes/_authenticated/brain'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as ApiPublicWhapiWebhookRouteImport } from './routes/api/public/whapi-webhook'
import { Route as ApiPublicHooksSendScheduledMessagesRouteImport } from './routes/api/public/hooks/send-scheduled-messages'
import { Route as ApiPublicHooksProcessBotJobsRouteImport } from './routes/api/public/hooks/process-bot-jobs'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserManagementRoute =
  AuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParticipantsRoute =
  AuthenticatedParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstructionsRoute =
  AuthenticatedInstructionsRouteImport.update({
    id: '/instructions',
    path: '/instructions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrainRoute = AuthenticatedBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWhapiWebhookRoute = ApiPublicWhapiWebhookRouteImport.update({
  id: '/api/public/whapi-webhook',
  path: '/api/public/whapi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendScheduledMessagesRoute =
  ApiPublicHooksSendScheduledMessagesRouteImport.update({
    id: '/api/public/hooks/send-scheduled-messages',
    path: '/api/public/hooks/send-scheduled-messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessBotJobsRoute =
  ApiPublicHooksProcessBotJobsRouteImport.update({
    id: '/api/public/hooks/process-bot-jobs',
    path: '/api/public/hooks/process-bot-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/brain': typeof AuthenticatedBrainRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/instructions': typeof AuthenticatedInstructionsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/participants': typeof AuthenticatedParticipantsRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/api/public/whapi-webhook': typeof ApiPublicWhapiWebhookRoute
  '/api/public/hooks/process-bot-jobs': typeof ApiPublicHooksProcessBotJobsRoute
  '/api/public/hooks/send-scheduled-messages': typeof ApiPublicHooksSendScheduledMessagesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/brain': typeof AuthenticatedBrainRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/instructions': typeof AuthenticatedInstructionsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/participants': typeof AuthenticatedParticipantsRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/whapi-webhook': typeof ApiPublicWhapiWebhookRoute
  '/api/public/hooks/process-bot-jobs': typeof ApiPublicHooksProcessBotJobsRoute
  '/api/public/hooks/send-scheduled-messages': typeof ApiPublicHooksSendScheduledMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/brain': typeof AuthenticatedBrainRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/instructions': typeof AuthenticatedInstructionsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/participants': typeof AuthenticatedParticipantsRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/_authenticated/user-management': typeof AuthenticatedUserManagementRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/whapi-webhook': typeof ApiPublicWhapiWebhookRoute
  '/api/public/hooks/process-bot-jobs': typeof ApiPublicHooksProcessBotJobsRoute
  '/api/public/hooks/send-scheduled-messages': typeof ApiPublicHooksSendScheduledMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/approvals'
    | '/brain'
    | '/groups'
    | '/instructions'
    | '/knowledge'
    | '/participants'
    | '/people'
    | '/settings'
    | '/usage'
    | '/user-management'
    | '/api/public/whapi-webhook'
    | '/api/public/hooks/process-bot-jobs'
    | '/api/public/hooks/send-scheduled-messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/activity'
    | '/approvals'
    | '/brain'
    | '/groups'
    | '/instructions'
    | '/knowledge'
    | '/participants'
    | '/people'
    | '/settings'
    | '/usage'
    | '/user-management'
    | '/'
    | '/api/public/whapi-webhook'
    | '/api/public/hooks/process-bot-jobs'
    | '/api/public/hooks/send-scheduled-messages'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/approvals'
    | '/_authenticated/brain'
    | '/_authenticated/groups'
    | '/_authenticated/instructions'
    | '/_authenticated/knowledge'
    | '/_authenticated/participants'
    | '/_authenticated/people'
    | '/_authenticated/settings'
    | '/_authenticated/usage'
    | '/_authenticated/user-management'
    | '/_authenticated/'
    | '/api/public/whapi-webhook'
    | '/api/public/hooks/process-bot-jobs'
    | '/api/public/hooks/send-scheduled-messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWhapiWebhookRoute: typeof ApiPublicWhapiWebhookRoute
  ApiPublicHooksProcessBotJobsRoute: typeof ApiPublicHooksProcessBotJobsRoute
  ApiPublicHooksSendScheduledMessagesRoute: typeof ApiPublicHooksSendScheduledMessagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-management': {
      id: '/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participants': {
      id: '/_authenticated/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof AuthenticatedParticipantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructions': {
      id: '/_authenticated/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof AuthenticatedInstructionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brain': {
      id: '/_authenticated/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof AuthenticatedBrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whapi-webhook': {
      id: '/api/public/whapi-webhook'
      path: '/api/public/whapi-webhook'
      fullPath: '/api/public/whapi-webhook'
      preLoaderRoute: typeof ApiPublicWhapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-scheduled-messages': {
      id: '/api/public/hooks/send-scheduled-messages'
      path: '/api/public/hooks/send-scheduled-messages'
      fullPath: '/api/public/hooks/send-scheduled-messages'
      preLoaderRoute: typeof ApiPublicHooksSendScheduledMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-bot-jobs': {
      id: '/api/public/hooks/process-bot-jobs'
      path: '/api/public/hooks/process-bot-jobs'
      fullPath: '/api/public/hooks/process-bot-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessBotJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedBrainRoute: typeof AuthenticatedBrainRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedInstructionsRoute: typeof AuthenticatedInstructionsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedParticipantsRoute: typeof AuthenticatedParticipantsRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedUserManagementRoute: typeof AuthenticatedUserManagementRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedBrainRoute: AuthenticatedBrainRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedInstructionsRoute: AuthenticatedInstructionsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedParticipantsRoute: AuthenticatedParticipantsRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedUserManagementRoute: AuthenticatedUserManagementRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWhapiWebhookRoute: ApiPublicWhapiWebhookRoute,
  ApiPublicHooksProcessBotJobsRoute: ApiPublicHooksProcessBotJobsRoute,
  ApiPublicHooksSendScheduledMessagesRoute:
    ApiPublicHooksSendScheduledMessagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
